backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "geo_cities"
        label: "Geo cities"
        file: "meta/geo_cities.json"
        description: "List of cities"
        fields:
          - name: cities
            label: Citites
            label_singular: "City"
            summary: "{{fields.name}}"
            widget: list
            min: 10
            max: 50
            fields:
              - label: "ID"
                name: "id"
                widget: "number"
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Timezone"
                name: "timezone"
                widget: "string"
      - name: "rosbilet_cities"
        label: "Rosbilet cities"
        file: "meta/rosbilet_cities.json"
        description: "List of cities"
        fields:
          - name: cities
            label: Citites
            label_singular: "City"
            summary: "{{fields.name}}"
            widget: list
            min: 10
            max: 50
            fields:
              - label: "ID"
                name: "id"
                widget: "number"
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Timezone"
                name: "timezone"
                widget: "string"
      - name: "rosbilet_matching"
        label: "Rosbilet Matching"
        file: "meta/rosbilet.json"
        description: "Rosbilet Matching description"
        fields:
          - name: matching
            label: Matching
            summary: "{{fields.geo_id}}"
            widget: list
            fields:
              - label: "Supplier"
                name: "supplier"
                widget: "string"
              - label: "Name"
                name: "name"
                widget: "string"
              - label: GeoID
                name: "geo_id"
                widget: relation
                collection: "meta"
                file: "geo_cities"
                searchFields:
                  - "cities.*.name"
                displayFields:
                  - "cities.*.name"
                valueField: "cities.*.id"
      - name: "cities"
        label: "Cities"
        file: "meta/cities.yml"
        description: "Atlas cities"
        fields:
          - name: cities
            label: Cities
            label_singular: "City"
            widget: list
            fields:
              - label: "ID"
                name: "id"
                widget: "number"
                hint: "ID города"
              - label: "Country code"
                name: "countryCode"
                widget: "string"
                hint: "Код страны"
              - label: "City"
                name: "city"
                widget: "string"
                hint: "Имя города"
              - label: "Timezone"
                name: "timezone"
                widget: "string"
                hint: "Таймзона"
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"
